export const SELLER_CONSENT_VERSION = 'seller-consent-v1';
export const SELLER_MINIMUM_AGE = 18;

export const SellerErrorCode = {
  USER_NOT_ACTIVE: 'SELLER_USER_NOT_ACTIVE',
  PHONE_NOT_VERIFIED: 'SELLER_PHONE_NOT_VERIFIED',
  PROFILE_INCOMPLETE: 'SELLER_PROFILE_INCOMPLETE',
  CONSENT_REQUIRED: 'SELLER_CONSENT_REQUIRED',
  BIRTH_DATE_INVALID: 'SELLER_BIRTH_DATE_INVALID',
  UNDERAGE: 'SELLER_UNDERAGE',
  VERIFICATION_REQUIRED: 'SELLER_VERIFICATION_REQUIRED',
  ACCESS_REVOKED: 'SELLER_ACCESS_REVOKED',
  ACCESS_ALREADY_REVOKED: 'SELLER_ACCESS_ALREADY_REVOKED',
  ACTIVE_REQUEST_EXISTS: 'SELLER_ACTIVE_REQUEST_EXISTS',
  INVALID_TRANSITION: 'SELLER_INVALID_TRANSITION',
  BREEDER_ACTIVE_REQUEST_EXISTS: 'BREEDER_ACTIVE_REQUEST_EXISTS',
  BREEDER_CALL_REQUIRED: 'BREEDER_SUCCESSFUL_CALL_REQUIRED',
  BREEDER_BASE_ROLE_REQUIRED: 'BREEDER_BASE_ROLE_REQUIRED',
} as const;
