export const PARROT_SALE_LISTING_MIN_IMAGES = 1;
export const PARROT_SALE_LISTING_MAX_IMAGES = 8;
export const PARROT_SALE_LISTING_MIN_QUANTITY = 1;
export const PARROT_SALE_LISTING_MAX_QUANTITY = 100;
