import { HttpException, HttpStatus } from '@nestjs/common';

export const ParrotSaleListingErrorCode = {
  NOT_FOUND: 'PARROT_SALE_LISTING_NOT_FOUND',
  NOT_EDITABLE: 'PARROT_SALE_LISTING_NOT_EDITABLE',
  IMAGE_REQUIRED: 'PARROT_SALE_LISTING_IMAGE_REQUIRED',
  IMAGE_LIMIT_REACHED: 'PARROT_SALE_LISTING_IMAGE_LIMIT_REACHED',
  IMAGE_NOT_FOUND: 'PARROT_SALE_LISTING_IMAGE_NOT_FOUND',
  INVALID_IMAGE_COUNT: 'PARROT_SALE_LISTING_INVALID_IMAGE_COUNT',
  INVALID_OPTION: 'PARROT_SALE_LISTING_INVALID_OPTION',
  INVALID_TRANSITION: 'PARROT_SALE_LISTING_INVALID_TRANSITION',
  INVALID_REVIEWER: 'PARROT_SALE_LISTING_INVALID_REVIEWER',
  PRICE_BELOW_REQUESTED: 'PARROT_SALE_LISTING_PRICE_BELOW_REQUESTED',
  PUBLICATION_CONFLICT: 'PARROT_SALE_LISTING_PUBLICATION_CONFLICT',
} as const;

export function parrotSaleListingError(
  status: HttpStatus,
  code: string,
  message: string,
): HttpException {
  return new HttpException({ statusCode: status, code, message }, status);
}
